### ISSUE TITLE
[WARN] Received packet of unknown type "0x43"

### ISSUE THREAD

**Issue by vordenken** [Hypfer/deye-microinverter-cloud-free#10]
Hello again :)

After my other issue (decreasing grid power today) I went through the logs and found a lot of warnings regarding this unknown packet.
<img width="626" alt="Bildschirmfoto 2023-10-22 um 14 21 30" src="https://github.com/Hypfer/deye-microinverter-cloud-free/assets/62395860/978f2773-326d-4113-baa7-d0a366951044">

Is this something to worry about? 
I'm using the Deye SUN600G3-EU-230 with firmware "MW3_16U_5406_2.32".

**Comment by Hypfer** [comment]
Nope, nothing to worry about.
I just haven't figured out what the payload of those messages means. iirc there's the SSID its connected to in there?
