### ISSUE TITLE
Is the faster could-reporting "fake"?

### ISSUE THREAD

**Issue by palto42** [Hypfer/deye-microinverter-cloud-free#8]
I was comparing the reported data using this great dummycloud software with the data I get via [deye-inverter-mqtt](https://github.com/kbialek/deye-inverter-mqtt). At least with the firmware 1.57 it seems that the faster reporting configured via AT command is not providing more measurements but just re-sending the same measurement more often.

If anyone else can confirm my observation, it might be worth to mention it in the README. I really like the `dummycloud`solution anyway, just wanted to set right expectations.

```
$ deye-logger-at-cmd -t <deye-ip>:48899 -xat AT+TIME
2023/10/15 07:18:59 * Connecting :0 -> <deye-ip>:48899...
2023/10/15 07:19:02 +ok=1,60,120
2023/10/15 07:19:03
```

In the below diagram you can see the two in comparison, showing that the data from dummycloud is also only changing about every 5 minutes.

![image](https://github.com/Hypfer/deye-microinverter-cloud-free/assets/12280188/a6e8535a-3369-46c0-8392-48b269b4ad03)

**Comment by Hypfer** [comment]
Sorry, yeah, can confirm.
I just forgot to remove that paragraph after testing it for a while
